Exercise on Functions:

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [1]:
# Simple Unit Converter

# Function to convert length
def convert_length(value, conversion_type):
    if conversion_type == 'm_to_ft':
        return value * 3.28084
    elif conversion_type == 'ft_to_m':
        return value / 3.28084
    else:
        print('Unsupported length conversion type.')
        return None

# Function to convert weight
def convert_weight(value, conversion_type):
    if conversion_type == 'kg_to_lbs':
        return value * 2.20462
    elif conversion_type == 'lbs_to_kg':
        return value / 2.20462
    else:
        print('Unsupported weight conversion type.')
        return None

# Function to convert volume
def convert_volume(value, conversion_type):
    if conversion_type == 'l_to_gal':
        return value * 0.264172
    elif conversion_type == 'gal_to_l':
        return value / 0.264172
    else:
        print('Unsupported volume conversion type.')
        return None

# Main program
print('Unit Converter')
print('Choose conversion type:')
print('1. Length (meters to feet or feet to meters)')
print('2. Weight (kilograms to pounds or pounds to kilograms)')
print('3. Volume (liters to gallons or gallons to liters)')

choice = input('Enter choice (1/2/3): ')
if choice not in ['1', '2', '3']:
    print('Invalid choice!')
else:
    try:
        value = float(input('Enter the value to convert: '))
        if choice == '1':
            conv_type = input("Enter conversion type ('m_to_ft' or 'ft_to_m'): ")
            result = convert_length(value, conv_type)
        elif choice == '2':
            conv_type = input("Enter conversion type ('kg_to_lbs' or 'lbs_to_kg'): ")
            result = convert_weight(value, conv_type)
        elif choice == '3':
            conv_type = input("Enter conversion type ('l_to_gal' or 'gal_to_l'): ")
            result = convert_volume(value, conv_type)

        if result is not None:
            print('Converted value:', result)
    except ValueError:
        print('Please enter a valid number!')

Unit Converter
Choose conversion type:
1. Length (meters to feet or feet to meters)
2. Weight (kilograms to pounds or pounds to kilograms)
3. Volume (liters to gallons or gallons to liters)
Enter choice (1/2/3): 1
Enter the value to convert: 12
Enter conversion type ('m_to_ft' or 'ft_to_m'): m_to_ft
Converted value: 39.37008


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [2]:
# Simple Math Operations on a List of Numbers

# Function to calculate the sum of numbers
def calculate_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

# Function to calculate the average of numbers
def calculate_average(numbers):
    """Returns the average of a list of numbers."""
    if len(numbers) == 0:
        print('Cannot calculate average of an empty list.')
        return None
    return sum(numbers) / len(numbers)

# Function to find the maximum value
def find_maximum(numbers):
    """Returns the maximum value from a list of numbers."""
    return max(numbers)

# Function to find the minimum value
def find_minimum(numbers):
    """Returns the minimum value from a list of numbers."""
    return min(numbers)

# Main program
print('Math Operations on a List of Numbers')
print('Choose an operation:')
print('1. Sum of numbers')
print('2. Average of numbers')
print('3. Maximum of numbers')
print('4. Minimum of numbers')

choice = input('Enter choice (1/2/3/4): ')
if choice not in ['1', '2', '3', '4']:
    print('Invalid choice!')
else:
    try:
        numbers = list(map(float, input('Enter numbers separated by spaces: ').split()))
        if len(numbers) == 0:
            print('The list of numbers cannot be empty!')
        else:
            if choice == '1':
                result = calculate_sum(numbers)
            elif choice == '2':
                result = calculate_average(numbers)
            elif choice == '3':
                result = find_maximum(numbers)
            elif choice == '4':
                result = find_minimum(numbers)

            if result is not None:
                print('Result:', result)
    except ValueError:
        print('Please enter valid numbers!')


Math Operations on a List of Numbers
Choose an operation:
1. Sum of numbers
2. Average of numbers
3. Maximum of numbers
4. Minimum of numbers
Enter choice (1/2/3/4): 2
Enter numbers separated by spaces: 12
Result: 12.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

In [3]:
def extract_every_other(lst):
    return lst[::2]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print(output_list)  # Output: [1, 3, 5]


[1, 3, 5]


2 Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [4]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
output_list = get_sublist(input_list, start_index, end_index)
print(output_list)  # Output: [3, 4, 5]


[3, 4, 5]


3 Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

In [5]:
def reverse_list(lst):
    return lst[::-1]

# Example usage:
input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)
print(output_list)  # Output: [5, 4, 3, 2, 1]


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [6]:
def remove_first_last(lst):
    return lst[1:-1]

# Example usage:
input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)
print(output_list)  # Output: [2, 3, 4]


[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

In [7]:
def get_first_n(lst, n):
    return lst[:n]

# Example usage:
input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)
print(output_list)  # Output: [1, 2, 3]


[1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [8]:
def get_last_n(lst, n):
    return lst[-n:]

# Example usage:
input_list = [1, 2, 3, 4, 5]
n = 2
output_list = get_last_n(input_list, n)
print(output_list)  # Output: [4, 5]


[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [9]:
def reverse_skip(lst):
    return lst[-2::-2]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)
print(output_list)  # Output: [5, 3, 1]


[5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [10]:
def flatten(lst):
    flattened_list = []
    for item in lst:
        if isinstance(item, list):
            flattened_list.extend(flatten(item))  # Recursively flatten if the item is a list
        else:
            flattened_list.append(item)
    return flattened_list

# Example usage:
nested_list = [[1, 2], [3, 4], [5]]
print(flatten(nested_list))  # Output: [1, 2, 3, 4, 5]


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

In [11]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

# Example usage:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print(access_nested_element(lst, indices))  # Output: 6


6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [12]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum if the item is a list
        else:
            total += item
    return total

# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))  # Output: 21


21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

In [13]:
def remove_element(lst, elem):
    return [[x for x in sublist if x != elem] for sublist in lst]

# Example usage
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
result = remove_element(lst, elem)
print(result)  # Output: [[1], [3], [4, 5]]


[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [14]:
def find_max(lst):
    max_val = float('-inf')  # Initialize with the smallest possible value

    def helper(sublist):
        nonlocal max_val
        for item in sublist:
            if isinstance(item, list):  # If item is a list, recursively call helper
                helper(item)
            else:
                max_val = max(max_val, item)  # Update max_val if item is greater

    helper(lst)
    return max_val

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)  # Output: 6


6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

In [15]:
def count_occurrences(lst, elem):
    count = 0

    def helper(sublist):
        nonlocal count
        for item in sublist:
            if isinstance(item, list):  # If item is a list, recursively call helper
                helper(item)
            elif item == elem:
                count += 1  # Increment count if item matches elem

    helper(lst)
    return count

# Example usage
nested_list = [[1, 2], [2, 3], [2, 4]]
elem = 2
result = count_occurrences(nested_list, elem)
print(result)  # Output: 3


3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [16]:
def deep_flatten(lst):
    flat_list = []

    def helper(sublist):
        for item in sublist:
            if isinstance(item, list):  # If item is a list, recursively call helper
                helper(item)
            else:
                flat_list.append(item)  # Append non-list items to the result

    helper(lst)
    return flat_list

# Example usage
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

In [17]:
def average_nested(lst):
    total_sum = 0
    count = 0

    def helper(sublist):
        nonlocal total_sum, count
        for item in sublist:
            if isinstance(item, list):  # If item is a list, recursively call helper
                helper(item)
            else:
                total_sum += item  # Add item to total sum
                count += 1  # Increment count of numbers

    helper(lst)

    return total_sum / count if count > 0 else 0  # Avoid division by zero

# Example usage
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)  # Output: 3.5


3.5


10 To - Do - NumPy

10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [18]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), 7)  # Example: 3x3 filled with 7
print("\nArray Filled with 7 (3x3):\n", fill_value_array)

# 4. Return a new array of zeros with same shape and type as a given array
example_array = np.array([[1, 2, 3], [4, 5, 6]])  # Example array
zeros_like_array = np.zeros_like(example_array)
print("\nZeros Array with Same Shape as Example Array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(example_array)
print("\nOnes Array with Same Shape as Example Array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array from List:\n", numpy_array)


Empty Array (2x2):
 [[2.3899923e-316 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as Example Array:
 [[0 0 0]
 [0 0 0]]

Ones Array with Same Shape as Example Array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy Array from List:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [19]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_to_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nMean of Random Array (size 30):", mean_value)

# 5. Create a 10x10 array with random values and find min and max values
random_matrix_10x10 = np.random.random((10, 10))
min_value = random_matrix_10x10.min()
max_value = random_matrix_10x10.max()
print("\nMinimum Value in 10x10 Random Matrix:", min_value)
print("Maximum Value in 10x10 Random Matrix:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 is the 5th element
print("\nZero Array with 5th Element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))  # Creating a 5x5 matrix of ones
border_array[1:-1, 1:-1] = 0  # Filling the inside with zeros
print("\n2D Array with Border 1 and Inside 0:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill alternating rows and columns
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of Random Array (size 30): 0.3869982323393647

Minimum Value in 10x10 Random Matrix: 0.0016055685753549875
Maximum Value in 10x10 Random Matrix: 0.9906095486213035

Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0 4 0 0 2 1]

2D Array with Border 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [20]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)

# 3. Multiply the array with an integer (e.g., multiply x by 3)
mult_x = x * 3
print("\nMultiplication of x by 3:\n", mult_x)

# 4. Find the square of each element of the array
square_x = np.square(x)
print("\nSquare of each element in x:\n", square_x)

# 5. Find the dot product between:
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y

print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along rows
concat_xy = np.concatenate((x, y), axis=0)  # Along row
print("\nConcatenation of x and y along rows:\n", concat_xy)

# Concatenate v and w along columns
concat_vw = np.vstack((v, w))  # Stacking as a column
print("\nConcatenation of v and w along columns:\n", concat_vw)

# 7. Try to concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}


In [21]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1:")
print(identity_matrix)

# Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:")
print(AB)
print("BA:")
print(BA)
print("Is AB ≠ BA?", not np.array_equal(AB, BA))

# Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:")
print(AB_T)
print("B^T * A^T:")
print(BT_AT)
print("Does (AB)^T = B^T * A^T?", np.array_equal(AB_T, BT_AT))

# Solve the system of linear equations using Inverse Method
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X using A^-1 * B
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("Solution for the system of equations:")
print(X)


A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Is AB ≠ BA? True
(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Does (AB)^T = B^T * A^T? True
Solution for the system of equations:
[ 2.  1. -2.]


# **10.2 Experiment: How Fast is Numpy?**

**1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [22]:
import time
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
python_add_time = time.time() - start_time

array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
array_addition = array1 + array2
numpy_add_time = time.time() - start_time

**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [24]:
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
python_mul_time = time.time() - start_time

start_time = time.time()
array_multiplication = array1 * array2
numpy_mul_time = time.time() - start_time

**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [23]:
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
python_dot_time = time.time() - start_time

start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
numpy_dot_time = time.time() - start_time

**4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [25]:
size_matrix = 1000
matrix1_np = np.arange(size_matrix**2).reshape(size_matrix, size_matrix)
matrix2_np = np.arange(size_matrix**2).reshape(size_matrix, size_matrix)

start_time = time.time()
matrix_multiplication_np = np.dot(matrix1_np, matrix2_np)
numpy_matrix_time = time.time() - start_time

In [26]:
print(f"Python Addition Time: {python_add_time:.5f} seconds")
print(f"NumPy Addition Time: {numpy_add_time:.5f} seconds")
print(f"Python Multiplication Time: {python_mul_time:.5f} seconds")
print(f"NumPy Multiplication Time: {numpy_mul_time:.5f} seconds")
print(f"Python Dot Product Time: {python_dot_time:.5f} seconds")
print(f"NumPy Dot Product Time: {numpy_dot_time:.5f} seconds")
print(f"NumPy Matrix Multiplication Time: {numpy_matrix_time:.5f} seconds")

Python Addition Time: 0.08566 seconds
NumPy Addition Time: 0.00532 seconds
Python Multiplication Time: 0.14679 seconds
NumPy Multiplication Time: 0.00564 seconds
Python Dot Product Time: 0.09373 seconds
NumPy Dot Product Time: 0.00178 seconds
NumPy Matrix Multiplication Time: 1.62386 seconds
